// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InfectedPeople struct {
	ID             string           `json:"id"`
	No             int              `json:"no"`
	ConfirmedDate  string           `json:"confirmed_date"`
	AgeGroup       int              `json:"age_group"`
	Sex            string           `json:"sex"`
	Jurisdiction   string           `json:"jurisdiction"`
	Residence      string           `json:"residence"`
	Occupation     string           `json:"occupation"`
	OnsetDate      string           `json:"onset_date"`
	TravelHistory  string           `json:"travel_history"`
	Remarks        string           `json:"remarks"`
	InfectedPlaces []*InfectedPlace `json:"infected_places"`
}

type InfectedPlace struct {
	ID               string `json:"id"`
	No               int    `json:"no"`
	InfectedPeopleID string `json:"infected_people_id"`
	Name             string `json:"name"`
	IsRelation       bool   `json:"is_relation"`
}
